version: '3.9'
services:
  app:
    image: golang:1.22.2
    container_name: <your-service-name>
    working_dir: /app
    environment:
      - GO111MODULE=on
    volumes:
      - ../../:/app
    env_file:
      - ../../.env
    ports:
      - "5050:5050"
    command: tail -f /dev/null
